### ISSUE TITLE
Error: skattemelding-api

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/dataservice-catalog#178]
Kan virke som det skyldes av et for stort svar fra mongoDB

> org.springframework.web.reactive.function.client.WebClientResponseException: 200 OK from GET https://api.swaggerhub.com/apis/skatteetaten/skattemelding-api/4.1.0 
> (...)
> org.springframework.core.io.buffer.DataBufferLimitException
> at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException ( LimitedDataBufferList.java:99 )

**Comment by KjerstiSteien** [comment]
@valosnah fant dere ut av dette? Fikk et spm fra Ragnhild som jeg lurer på om kan være knyttet til samme feilen. Gjelder samme API-beskrivelse og en 500-feil.

**Comment by valosnah** [comment]
Gjenskapt i staging. Skjer når man prøver å importere veldig stor spesifikasjon via lenke

**Comment by valosnah** [comment]
Flyttes til ready mens vi avventer prioritet
