### ISSUE TITLE
Legge inn liste av mediatyper for datatjenester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog#36]
hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/411

I referansedata skal vi støtte en liste over mediatyper brukerne kan benytte seg av.

F.eks fra:
https://www.iana.org/assignments/media-types/media-types.xml

NB! Dette skal også brukes på distribusjoner fra Datasettregistrering.

**Comment by azaxarov** [comment]
@lillelars er denne issue fortsatt aktuell?

**Comment by lillelars** [comment]
Er nå gjort både for datatjenesteregistrering og datasettregistrering. Lukker derfor denne
