### ISSUE TITLE
Legg til støtte for externalDocs fra openAPI specification

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataservice-catalog#62]
externalDocs er ein url. Denne skal inn i dcat:landingPage og ser ikkje ut til å bli importert frå openAPI specification.

**Comment by lillelars** [comment]
@stigbd har du mulighet til å verifisere denne og lukke den hvis det er som den skal?
Tror ikke vi viser dette feltet i registrering

**Comment by stigbd** [comment]
Det ser ikkje ut til at vi har støtte for denne, så det er stadig et issue.

**Comment by lillelars** [comment]
@NilsOveTen Denne speccen inneholder externalDocs - men får det ikke med i registreringsløsning.

https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/Spesifisert%20Summert%20Skattegrunnlag%20v1.0.0.json

**Comment by stigbd** [comment]
Og denne:
https://raw.githubusercontent.com/brreg/openAPI/master/specs/fdk.json

**Comment by NilsOveTen** [comment]
@stigbd og @lillelars Jeg testet begge linkene i staging, det fungerte der...

**Comment by lillelars** [comment]
@stigbd @joebrreg 
det blir med her foreløpig.... : Trenger vi gui på dette mener du?
![image](https://user-images.githubusercontent.com/39513382/92565354-cbf53c80-f27a-11ea-8663-22114306a4f5.png)

**Comment by stigbd** [comment]
Det må kome ut i høste-endepunktet. 

Viss det er slik at @NilsOveTen har verifisert dette, er er all good.

**Comment by lillelars** [comment]
@stigbd det har jeg verifisert allerede.
Lulkker dermed saken.

**Comment by lillelars** [comment]
externalDocs er med hele løpet. lukker saken.

**Comment by stigbd** [comment]
Det er mogleg å skreiv issuet litt dårleg. Det var to påstander:
1. externalDocs er ein url. Denne ser ikkje ut til å bli importert frå openAPI specification.
2. externalDocs er ein url. Denne skal inn i dcat:landingPage.

Det ser ut til at 1. er verifisert at fungerer. Det eg eigentleg meinte å opprette issue på, var 2. Altså at externalDocs skal ut i hausteendepunktet som dcat:landingPage.

For eksempelet du viser over, ser dcat:DataService slik ut:
```
<https://dataservice-catalog.staging.fellesdatakatalog.digdir.no/data-services/5f587bc2dbffd544ae76a5e6>
        a                         dcat:DataService ;
        dct:description           "Spesifisert summert XXXskattegrunnlag inneholder summert informasjon om en skatteyters inntekt, formue og fradrag og formuesfradrag, med spesifikasjoner."@nb ;
        dct:title                 "Spesifisert summert YYYskattegrunnlag API"@nb ;
        dcat:contactPoint         [ a                          vcard:Organization ;
                                    vcard:fn                   "Contact information | (910258028)" ;
                                    vcard:hasOrganizationName  "Brukerstøtte datasamarbeid"@nb ;
                                    vcard:hasURL               <https://www.skatteetaten.no/bedrift-og-organisasjon/starte-og-drive/ZZZbestill-attester-og-tilgang-pa-data/skatteetatens-datasamarbeid/skatte--og-inntektsopplysninger/brukerstotte-datasamarbeid/>
                                  ] ;
        dcat:endpointDescription  <https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/Spesifisert%20Summert%20Skattegrunnlag%20v1.0.0.json> ;
        dcat:endpointURL          <https://api.skatteetaten.no> , <https://api-at.sits.no> .
```
Følgande trippel manglar:
```
<https://dataservice-catalog.staging.fellesdatakatalog.digdir.no/data-services/5f587bc2dbffd544ae76a5e6>
        a                         dcat:DataService ;
            dcat:landingPage   <https://skatteetaten.github.io/datasamarbeid-api-dokumentasjon/ÆÆÆdata_spesifisertsummertskattegrunnlag.html>
.
```
Sjekk https://dataservice-catalog.staging.fellesdatakatalog.digdir.no/catalogs

**Comment by NilsOveTen** [comment]
Ser ut til at alt har blitt lagt til, men frontend fjerner externalDocs om det blir gjort endringer etter importering. Skal få opp en pr i dataservice-catalog-gui

**Comment by stigbd** [comment]
Det ser ut til at import no genererer landingPage. Slik sett er issuet løyst.

Vi bør imidlertid "re-generer" landingPage for spesifikasjoner som alt er importert og har externalDocs.
