### ISSUE TITLE
Add functionality to import dataservice formats in dataservice-catalog

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/dataservice-catalog#74]
Når bruker importerer en spesifikasjon blir ikke formatene tatt med.

https://github.com/informasjonsforvaltning/dataservice-catalog-gui/issues/57 tar for seg frontend av dette.

**Comment by lillelars** [comment]
Testet in staging, chrome. Fungerer nå som forventet. Lukker saken.
