### ISSUE TITLE
Utbedring av spring-security i dataservice-catalog

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataservice-catalog#79]
- [x] Alle feil ifbm token svarer nå med 500, burde svare med enten 401 eller 403
- [x] Legg til audience-sjekk
- [x] Oppdater spring-boot og spring-security

**Comment by shenluna** [comment]
Testet OK, eks https://www.staging.fellesdatakatalog.digdir.no/dataservices/3056c41b-f9f4-345a-92b5-222575b6a6bd
